### ISSUE TITLE
SEO optimizations

### ISSUE THREAD

**Issue by anthonymonori** [anthonymonori/monori-me#3]
Use the title and description of the individual page to be indexed instead of a global header image, title and description. This will fix the social sharing experience where the page would have it's own thumbnail associated with it with title and description

**Comment by antalindisguise** [comment]
Otherwise according to Lighthouse the SEO is well optimised, still the above stands

![Screenshot 2019-12-01 at 10 31 01 AM](https://user-images.githubusercontent.com/935897/69912172-c2a28e00-1425-11ea-9836-4b447ad95b95.png)
